[package]
name = "rustbucket"
version = "0.1.0"
authors = ["Matthew Mage <sciguymjm@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
boxcars = "0.3.2"
failure = "0.1.1"
libc = "0.2.55"

[build-dependencies]
cbindgen = "0.8.0"

[lib]
name = "rustbucket"
crate-type = ["dylib"]